name: sigv4
description: Library for signing AWS requests with Signature Version 4, with both convenience wrappers/classes and cryptography methods
homepage: https://github.com/arnemolland/sigv4

version: 5.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  http: ^0.13.3
  convert: ^3.0.0
  dio: ^4.0.0-prev3

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
  mockito: ^5.0.9
  dotenv: ^3.0.0
  path: ^1.8.0
